/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { Config, ConfigService } from './config.service';
import { BaseComponent } from 'src/app/base/component/base/base.component';
import { LoggerService } from 'src/app/base/service/logger.service';

@Component({
  selector: 'app-config',
  templateUrl: './config.component.html',
  providers: [ConfigService],
  styles: ['.error {color: red;}'],
})
export class ConfigComponent extends BaseComponent {
  error: any;
  headers: string[];
  config: Config;

  constructor(
    private configService: ConfigService,
    _loggerService: LoggerService,
  ) {
    super('ConfigComponent', _loggerService);
    this.WriteDebugLog('ConfigComponent => constructor');
  }

  clear() {
    this.WriteDebugLog('ConfigComponent => clear');
    this.config = undefined;
    this.error = undefined;
    this.headers = undefined;
  }

  showConfig() {
    this.WriteDebugLog('ConfigComponent => showConfig');
    this.configService.getConfig().subscribe(
      (data: Config) => (this.config = { ...data }), // success path
      error => (this.error = error), // error path
    );
  }

  showConfig_v1() {
    this.WriteDebugLog('ConfigComponent => showConfig_v1');
    this.configService.getConfig_1().subscribe(
      (data: Config) =>
        (this.config = {
          version: data.version,
        }),
    );
  }

  showConfig_v2() {
    this.WriteDebugLog('ConfigComponent => showConfig_v2');
    this.configService
      .getConfig()
      // clone the data object, using its known Config shape
      .subscribe((data: Config) => (this.config = { ...data }));
  }

  showConfigResponse() {
    this.WriteDebugLog('ConfigComponent => showConfigResponse');
    this.configService
      .getConfigResponse()
      // resp is of type `HttpResponse<Config>`
      .subscribe(resp => {
        // display its headers
        const keys = resp.headers.keys();
        this.headers = keys.map(key => `${key}: ${resp.headers.get(key)}`);

        // access the body directly, which is typed as `Config`.
        this.config = { ...resp.body };
      });
  }
  makeError() {
    this.WriteDebugLog('ConfigComponent => makeError');
    this.configService
      .makeIntentionalError()
      .subscribe(null, error => (this.error = error));
  }
}
