/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from "@angular/router";
import { HeaderComponent } from "./header.component";
import { FormBuilder } from '@angular/forms';
import { UserProfileDetailsComponent } from 'src/app/base/userprofile/userprofile-details.component';
import { UserProfileComponent } from 'src/app/base/userprofile/userprofile.component';
import { ReleaseNotesComponent } from '../release-notes/release-notes.component';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { NgxBootStrapModule } from '../modules/ngxbootstrap.module';
import { ApplicationCommonModule } from 'src/app/modules/applicationcommon/applicationcommon.module';
import { NotificationPopupComponent } from 'src/app/modules/applicationcontrols/Controls/notification-popup/notification-popup.component';
import { ApplicationControlsModule } from 'src/app/modules/applicationcontrols/applicationcontrols.module';

@NgModule({
    imports: [
        RouterModule,
        CommonModule,
        BrowserModule,
        FormsModule,
        NgxBootStrapModule,
        ApplicationCommonModule,
        ApplicationControlsModule
    ],
    exports: [
        HeaderComponent
    ],
    declarations: [
        HeaderComponent,
        UserProfileComponent,
        ReleaseNotesComponent,
        UserProfileDetailsComponent,
        NotificationPopupComponent
    ],
    providers: [FormBuilder],
    schemas: [
        CUSTOM_ELEMENTS_SCHEMA
    ]
})
export class HeaderModule {
    constructor() {

    }
}
