/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>
using MongoDB.Driver;

namespace FMP.Repository.Interface
{
    public interface IFMPContext
    {
        IMongoCollection<FMP.Model.CounterDataModel.Counter> Counter { get; }

        IMongoCollection<FMP.Model.UserProfileDataModel.UserProfile> UserProfiles { get; }
        IMongoCollection<FMP.Model.LayoutDataModel.Layout> Layouts { get; }
        IMongoCollection<FMP.Model.LayoutDataModel.UserLayoutPreference> UserLayoutPreferences { get; }

        IMongoCollection<FMP.Model.UserDataModel.User> User { get; }
        IMongoCollection<FMP.Model.RoleDataModel.Role> Role { get; }
        IMongoCollection<FMP.Model.RoleDataModel.Claim> Claim { get; }
        IMongoCollection<FMP.Model.RoleDataModel.CMMSRole> CMMSRole { get; }
        //IMongoCollection<FMP.Model.EquipmentDataModel.EquipmentType> EquipmentType { get; }

        IMongoCollection<FMP.Model.Common.ReleaseNoteModel> ReleaseNote { get; }

    }
}
