'use strict';
/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
// This file is required by karma.conf.js and loads recursively all the .spec and framework files
Object.defineProperty(exports, '__esModule', { value: true });
require('zone.js/dist/zone-testing');
var testing_1 = require('@angular/core/testing');
var testing_2 = require('@angular/platform-browser-dynamic/testing');
// First, initialize the Angular testing environment.
testing_1
  .getTestBed()
  .initTestEnvironment(
    testing_2.BrowserDynamicTestingModule,
    testing_2.platformBrowserDynamicTesting(),
  );
// Then we find all the tests.
var context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
//# sourceMappingURL=test.js.map
