/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using MongoDB.Bson;

namespace FMP.Model.UserDataModel
{
    [CollectionName("Users")]
    public class User
    {
        /// <summary>
        ///     Id auto generated by Mongo DB
        /// </summary>
        public ObjectId _id { get; set; }

        /// <summary>
        ///     GIN / Unique Identifier
        /// </summary>
        public int GIN { get; set; }

        /// <summary>
        ///     User Alias/Name
        /// </summary>
        public string Alias { get; set; }

        /// <summary>
        ///     First Name
        /// </summary>
        public string FirstName { get; set; }

        /// <summary>
        ///     Last Name
        /// </summary>
        public string LastName { get; set; }

        /// <summary>
        ///     User Email
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        ///     IsAdmin - If user is admin user
        /// </summary>
        public bool IsAdmin { get; set; }

        /// <summary>
        ///     IsDeveloper - If user is developer
        /// </summary>
        public bool IsDeveloper { get; set; }

        /// <summary>
        ///     IsActive - If user is active
        /// </summary>
        public bool IsActive { get; set; }
    }
}