/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using System;
using System.Collections.Generic;
using FMP.Model.UserProfileDataModel;
using MongoDB.Bson;

namespace FMP.Model.LayoutDataModel
{
    /// <summary>
    ///     Layout Class
    /// </summary>
    public class Layout
    {
        public ObjectId _id { get; set; }

        /// <summary>
        ///     Layout ID
        /// </summary>
        public int LayoutID { get; set; }

        public ObjectId LayoutGuid { get; set; }

        /// <summary>
        ///     User Ldap
        /// </summary>
        public string UserID { get; set; }

        /// <summary>
        ///     Application Name (AM/PNS/ADM)
        /// </summary>
        public string ApplicationName { get; set; }

        /// <summary>
        ///     Type of Layout (System/Private/Public)
        /// </summary>
        public string LayoutType { get; set; }

        /// <summary>
        ///     Layout Name
        /// </summary>
        public string LayoutName { get; set; }

        /// <summary>
        ///     Information about the columns that layout contains
        /// </summary>
        public List<LayoutConfig> LayoutConfigs { get; set; }

        /// <summary>
        ///     Sort Details of grid/layout columns
        /// </summary>
        public List<SortConfigs> Sort { get; set; }

        /// <summary>
        ///     Group Details of grid/layout columns
        /// </summary>
        public List<GroupConfigs> Group { get; set; }

        /// <summary>
        ///     Filter Details of grid/layout columns
        /// </summary>
        public FilterConfigs Filter { get; set; }

        public List<int> Lock { get; set; }

        public static Layout From(LayoutData layoutData,string userId)
        {
            return new Layout
            {
                UserID = userId,
                LayoutGuid = ObjectId.GenerateNewId(),
                ApplicationName = layoutData.ApplicationName,
                LayoutName = layoutData.LayoutName,
                LayoutConfigs = layoutData.LayoutConfigs,
                Sort = layoutData.Sort,
                Group = layoutData.Group,
                Filter = layoutData.Filter
            };
        }
    }
}