/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using System;
using System.Collections.Generic;
using System.Text;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;

namespace FMP.Model.LayoutDataModel
{
    /// <summary>
    /// Layout Config
    /// </summary>
    public class LayoutConfig
    {
        public string LayoutName { get; set; }
        public bool IsDefault { get; set; }
        public bool disabled { get; set; }
        public int ColumnId { get; set; }
        public string ColumnName { get; set; }
        public string FieldName { get; set; }
        public bool IsLocked { get; set; }
        public int Sequence { get; set; }
        public string ToolTip { get; set; }

    }
    /// <summary>
    /// Filter Config
    /// </summary>
    public class FilterConfigs
    {
        public List<FiltersFields> Filters { get; set; }
        public string Logic { get; set; }
    }

    /// <summary>
    /// Filters Field
    /// </summary>
    public class FiltersFields
    {
        public string Field { get; set; }
        public string Operator { get; set; }
        public string Value { get; set; }
        public List<FiltersFields> Filters { get; set; }
        public string Logic { get; set; }
    }

    /// <summary>
    /// Group Config
    /// </summary>
    public class GroupConfigs
    {
        public string dir { get; set; } = "asc";
        public string field { get; set; }
    }
    /// <summary>
    /// Sort Config
    /// </summary>
    public class SortConfigs
    {
        public string dir { get; set; }
        public string field { get; set; }
    }
}
