/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { Injectable, EventEmitter } from '@angular/core';
import { DataService } from '../service/data.service';
import { HttpClient } from '@angular/common/http';
import { NgxSpinnerService } from 'ngx-spinner';
import { LoggerService } from '../service/logger.service';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root',
})
export class LoaderService extends DataService {
  constructor(
    private _http: HttpClient,
    public spinner: NgxSpinnerService,
    _loggerService: LoggerService,
  ) {
    super('LoaderService', '', _http, _loggerService);
    this.restLoading.subscribe((loading: boolean) => {
      if (loading) {
        this.currentlyLoading++;
      } else {
        this.currentlyLoading--;
      }

      if (this.currentlyLoading === 0) {
        this.hideSpinner();
      } else {
        this.showSpinner();
      }
    });
  }

  public restLoading = new EventEmitter<boolean>();
  private currentlyLoading = 0;
  public LoadingText: string;
  displayed: boolean;

  public isLoading() {
    return this.displayed;
  }

  showSpinner() {
    this.displayed = true;
    this.spinner.show();
  }
  hideSpinner() {
    // If called from outside we need to force the counter to be zero
    this.currentlyLoading = 0;
    this.displayed = false;
    this.spinner.hide();
  }
}
