/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */

// this was interface but may need to do this better
export interface IBaseMapperViewModel {
  name: string;
  createdBy: string;
  createdDate: string;
  modifiedBy: string;
  id: string;
}

export interface ISitePermission {
    applicationName: string;
    edit: boolean;
    view: boolean;
}
export interface IWhitelistedSiteModel {
    code: string;
    facilityId?: string;
    facility?: any;
    segmentCode: string;
    businessView?: any;
    businessGroup: string;
    businessCode: string;
    activeCMMS: string;
    permissions: Array<ISitePermission>;
    createdBy: string;
    lastUpdatedDateTime: Date;
    PlanandSchedule: ISitePermission;
    ActivityMonitor: ISitePermission;
}

export class WhitelistedSitesModel implements IWhitelistedSiteModel {
    constructor(private siteObj: IWhitelistedSiteModel) {
        this.code = siteObj.code;
        this.facilityId = siteObj.facilityId;
        this.businessGroup = this.businessGroup;
        this.businessCode = this.businessCode;
        this.activeCMMS = siteObj.activeCMMS;
        this.createdBy = siteObj.createdBy;
        this.lastUpdatedDateTime = siteObj.lastUpdatedDateTime;
    }
    code: string;
    facilityId?: string;
    segmentCode: string;
    businessGroup: string;
    businessCode: string;
    activeCMMS: string;
    permissions: Array<ISitePermission>;
    createdBy: string;
    lastUpdatedDateTime: Date;
    PlanandSchedule: ISitePermission;
    ActivityMonitor: ISitePermission;
}

export interface WhiteListedSites {
    SiteName: string;
    Site_ID: string;
    cmms: string;
    permissions: Array<ISitePermission>;
    segment: string;
    siteObj: WhitelistedSitesModel;
    siteSegmentName: string;
    workLocation: string;
}

export interface EnabledSitesSubset {
    siteCode: string;
    siteKey: string;
    url: {
        href: string;
        rel: string;
        type: string;
    };
}

export interface EnabledSites {
    context: string;
    sites: Array<EnabledSitesSubset>;
}

