import { MateoQueue } from "../models/mateoQueue";

/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
export class FMPBaseException {
    referenceName: string;
    errorMessage: string;
    errorInstance: any;
    parameters: Map<string, any>;

    constructor(refName: string, errorMessage: string, error?: any, params?: Map<string, any>) {
        this.referenceName = refName;
        this.errorMessage = errorMessage;
        this.errorInstance = error;
        this.parameters = params;
    }
}
export class InputException extends FMPBaseException {
    constructor(refName: string, errorMessage: string, error?: any, params?: Map<string, any>) {
        super(refName, errorMessage, error, params);
    }
}

export class ApplicationException extends FMPBaseException {
    constructor(refName: string, errorMessage: string, error?: any, params?: Map<string, any>) {
        super(refName, errorMessage, error, params);
        if (!this.parameters) {
            this.parameters = new Map<string, any>();
        }
    }
}

export class MateoQueueException extends ApplicationException {
    constructor(refName: string, errorMessage: string, queueItem: MateoQueue<any>, error?: any, params?: Map<string, any>) {
        super(refName, errorMessage, error, params);
        if (!this.parameters) {
            this.parameters = new Map<string, any>();
        }
        this.mateoQueueItem = queueItem;
    }
    mateoQueueItem: MateoQueue<any>;
}
