#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591
using System.Threading.Tasks;

namespace FMP.Service
{
    public class CreateEntityHandler<T> :
        HandlerBase<T>,
        ICommandHandler<ICreateCommand<T>> where T : class
    {
        private readonly IKeyGenerator<T> _keyGenerator;

        public CreateEntityHandler(
            IMongoDbCollection<T> userProfiles,
            IKeyGenerator<T> keyGenerator) :
            base(userProfiles)
        {
            _keyGenerator = keyGenerator;
        }

        public async Task<bool> Handle(ICreateCommand<T> command)
        {
            await _keyGenerator.Generate(command.NewEntity());

            await Collection.InsertOneAsync(command.NewEntity());
            return true;
        }
    }
}