#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591
using MongoDB.Driver;

namespace FMP.Service
{
    public class DeleteCommand<T> : IDeleteCommand<T> where T : class
    {
        protected DeleteCommand()
        {

        }
        public static DeleteCommand<T> WithFilter(IQuery<T> filter)
        {
            var obj = new DeleteCommand<T>();
            obj.FilterInt = filter;
            return obj;
        }

        protected IQuery<T> FilterInt;

        public FilterDefinition<T> FilterDefinition()
        {
            return FilterInt.FilterDefinition();
        }
    }
}