#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

using System.Collections.Generic;
using System.Linq;
using MongoDB.Driver;

#pragma warning disable 1591

namespace FMP.Service
{
    public abstract class UpdateBase<T> : IUpdateCommand<T> where T : class
      
    {
        protected UpdateBase()
        {
            Updates = new List<UpdateDefinition<T>>();
            UpdateBuilder = Builders<T>.Update;
        }

        protected List<UpdateDefinition<T>> Updates;

        protected UpdateDefinitionBuilder<T> UpdateBuilder ;

        protected IQuery<T> FilterInt;

        public FilterDefinition<T> FilterDefinition()
        {
            return FilterInt.FilterDefinition();
        }

        public UpdateDefinition<T> UpdateDefinition()
        {
            return UpdateBuilder.Combine(Updates); 
        }

        public bool IsValid()
        {
            return Updates.Any();
        }

        public bool IsManyUpdate { get; protected set; }
    }

    
}