/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import {
    AuthModule, OidcSecurityService, OpenIdConfiguration,
    OidcConfigService, AuthWellKnownEndpoints, ConfigResult
} from 'angular-auth-oidc-client';
import { FMPHelper } from 'src/Constants/helpers';

export class AuthenticationHelper {
    public static CreateOIDCConfigurationInstance(oidcSecurityService: OidcSecurityService, oidcConfigService: OidcConfigService) {
        oidcConfigService.onConfigurationLoaded.subscribe((configResult: ConfigResult) => {
            const openIDImplicitFlowConfiguration:OpenIdConfiguration = {
                auto_userinfo : FMPHelper.AuthenticationSettings.AutoGetUserInfo,
                stsServer: FMPHelper.AuthenticationSettings.STSServer,
                redirect_url: window.location.origin,
                post_logout_redirect_uri: window.location.origin + '/' + FMPHelper.AuthenticationSettings.PostLogoutRedirectUrl,
                client_id: FMPHelper.AuthenticationSettings.ClientID,
                response_type: FMPHelper.AuthenticationSettings.ResponseType,
                scope: FMPHelper.AuthenticationSettings.Scope,
                post_login_route: FMPHelper.AuthenticationSettings.PostLoginRoute,
                forbidden_route: FMPHelper.AuthenticationSettings.ForbiddenRoute,
                unauthorized_route: FMPHelper.AuthenticationSettings.UnAuthorizedRoute,
                trigger_authorization_result_event: FMPHelper.AuthenticationSettings.TriggerAuthorizationResultEvent,
                log_console_warning_active: FMPHelper.AuthenticationSettings.LogConsoleWarningActive,
                log_console_debug_active: FMPHelper.AuthenticationSettings.LogConsoleDebugActive,
                max_id_token_iat_offset_allowed_in_seconds
                    : FMPHelper.AuthenticationSettings.MaxIdTokenIATOffsetAllowedInSeconds,
                start_checksession: FMPHelper.AuthenticationSettings.StartCheckSession,
                history_cleanup_off: false,
                silent_renew: FMPHelper.AuthenticationSettings.SilentRenew,
                silent_renew_url: window.location.origin + '/' + FMPHelper.AuthenticationSettings.SilentRenewUrl,
                silent_renew_offset_in_seconds: FMPHelper.AuthenticationSettings.SilentRenewOffsetInSeconds,
                //isauthorizedrace_timeout_in_seconds: 10,
            }
         
            //setWellKnownEndpoints(oidcConfigService.wellKnownEndpoints);
            oidcSecurityService.setupModule(openIDImplicitFlowConfiguration, configResult.authWellknownEndpoints);

            oidcSecurityService.stopCheckingSilentRenew();// we stop it here but start it in home component to keep loops from happening in Edge
        });
        //setTimeout(() => {
        //    console.log('hello');
       // }, 1000);
    }

    public static GetLocationHash(): string {
        if (typeof location !== 'undefined' && !FMPHelper.StringIsNullOrWhiteSpace(window.location.hash)) {
            return window.location.hash;
        }
        return null;
    }

    public static GetTokenHash(): string {
        if (typeof location !== 'undefined' && !FMPHelper.StringIsNullOrWhiteSpace(window.location.hash)) {
            const indexHash = window.location.hash.indexOf('id_token');
            return indexHash > -1 && window.location.hash.substr(indexHash);
        }
    }
}

export enum AuthStorageKeys {
    FMP_AUTH_AUTHNONCE = 'FMP_AUTH_AUTHNONCE',
    FMP_AUTH_AUTHORIZATIONDATA = 'FMP_AUTH_AUTHORIZATIONDATA',
    FMP_AUTH_AUTHORIZATIONDATAIDTOKEN = 'FMP_AUTH_AUTHORIZATIONDATAIDTOKEN',
    FMP_AUTH_AUTHORIZATIONRESULT = 'FMP_AUTH_AUTHORIZATIONRESULT',
    FMP_AUTH_AUTHSTATECONTROL = 'FMP_AUTH_AUTHSTATECONTROL',
    FMP_AUTH_SESSION_STATE = 'FMP_AUTH_SESSION_STATE',
    FMP_AUTH_STORAGE_SILENT_RENEW_RUNNING = 'FMP_AUTH_STORAGE_SILENT_RENEW_RUNNING',
    FMP_AUTH_USERDATA = 'FMP_AUTH_USERDATA',
    FMP_AUTH__ISAUTHORIZED = 'FMP_AUTH__ISAUTHORIZED',
}
