/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';

import { KendoControlModule } from '../../base/modules/kendocontrols.module';
import { TreeViewModule } from '@progress/kendo-angular-treeview';
import { NgMultiSelectDropDownModule } from 'ng-multiselect-dropdown';
import { DialogsModule } from '@progress/kendo-angular-dialog';
import { ProgressPanelComponent } from './digitalmaint/progresspanel.component';
import { ProgressPanelService } from './digitalmaint/progresspanel.service';
import { DigitalMaintOverviewComponent } from './digitalmaint/digitalmaintoverview.component';
import { TlmUtilsRoutingModule } from './tlm-utils-routing.module';
import { MappingModule } from './mappingmodule/mapping.module';
import { DashboardComponent } from './dashboard/dashboard.component';
import { TranslateModule } from '@ngx-translate/core';
import { HistorianProvisionComponent } from './historianutil/historianprovision.component';
import { ClassificationComponent } from './classification/classification.component';
import { StandardWorkComponent } from './standardwork/standardwork.component';
import { EquipmentHealthComponent } from './equipmenthealth/equipmenthealth.component';
import { EquipmentHealthService } from './equipmenthealth/equipmenthealth.service';
import { ChartsModule } from '@progress/kendo-angular-charts';
import { EquipmentBrowserComponent } from './equipmentbrowser/equipmentbrowser.component';
import { EpisodeBrowserComponent } from './episode/episodebrowser.component';
import { EpisodePointsComponent } from './episode/episodepoints.component';
import { EquipmentChannelComponent } from './equipmentchannel/equipmentchannel.component';
import { EquipmentChannelService } from './equipmentchannel/equipmentchannel.service';
import { EquipmentBrowserService } from './equipmentbrowser/equipmentbrowser.service';
import { ClassificationService } from './classification/classification.service';
import { StandardWorkService } from './standardwork/standardwork.service';
import { UploadComponent } from './standardwork/upload/upload.component';
import { LasFileUploadComponent } from './digitalmaint/upload/lasfileupload.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { EpisodeBrowserService } from './episode/episodebrowser.service';
import { WorkOrderService } from './workorder/workorder.service';
import { WorkOrderBrowserComponent } from './workorder/workorderbrowser.component';
import { UserSentimentService } from './usersentiment/usersentiment.service';
import { UserSentimentComponent } from './usersentiment/usersentiment.component';
import { ProgressBarModule } from '@progress/kendo-angular-progressbar';
import { EpicV3Service } from './epicv3browser/epicV3.service';
import { EpicV3Component } from './epicv3browser/epicV3.component';
import { ScheduleradminComponent } from './scheduleradmin/scheduleradmin.component';
import { ScheduleradminService } from './scheduleradmin/scheduleradmin.service';

import { LayoutModule } from "@progress/kendo-angular-layout";
import { WindowModule } from "@progress/kendo-angular-dialog";
import { ButtonsModule } from "@progress/kendo-angular-buttons";
import { BrowserAnimationsModule } from "@angular/platform-browser/animations";
import { HistorianManagementComponent } from './historianmanagement/historianmanagement.component';
import { InfluxDbMappingService } from './historianmanagement/influx-db-mapping.service';
import { ConflictManagementComponent } from './conflictmanagment/conflictmanagement.component';
import { ConflictManagementService } from './conflictmanagment/conflictmanagement.service';
import { TooltipModule } from "@progress/kendo-angular-tooltip";
import { AddschedulerjobComponent } from './scheduleradmin/addschedulerjob/addschedulerjob.component';
import { UpdateschedulerjobComponent } from './scheduleradmin/updateschedulerjob/updateschedulerjob.component';
import { AuditLogService } from './auditlogging/auditlogging.service';
import { AuditLogComponent} from './auditlogging/auditlogging.component';
import { ChannelDefinitionComponent } from './channeldefinition/channeldefinition.component';
import { ChannelDefinitionService } from './channeldefinition/channeldefinition.service';
import { ChannelDefinitionUtilComponent } from './channeldefinitionutil/channeldefinitionutil.component';

@NgModule({
    declarations: [        
        EpicV3Component,
        HistorianProvisionComponent,
        DashboardComponent,
        ClassificationComponent,
        StandardWorkComponent,
        EquipmentBrowserComponent,
        EpisodeBrowserComponent,
        EquipmentChannelComponent,
        EquipmentHealthComponent,
        UploadComponent,
        LasFileUploadComponent,
        DigitalMaintOverviewComponent,
        WorkOrderBrowserComponent,
        EpisodePointsComponent,
        ProgressPanelComponent,
        UserSentimentComponent,
        ScheduleradminComponent,
        HistorianManagementComponent,
        ConflictManagementComponent,
        AddschedulerjobComponent,
        UpdateschedulerjobComponent,
        AuditLogComponent,
        ChannelDefinitionComponent,
        ChannelDefinitionUtilComponent
    ],
    providers: [
        EpicV3Service,
        EquipmentBrowserService,
        EquipmentHealthService,
        ClassificationService,
        StandardWorkService,
        EpisodeBrowserService,
        WorkOrderService,
        EquipmentChannelService,
        ProgressPanelService,
        UserSentimentService,
        ScheduleradminService,
        InfluxDbMappingService,
        ConflictManagementService,
        AuditLogService,
        ChannelDefinitionService
    ],
  imports: [
    CommonModule,
    BrowserModule,
    HttpClientModule,
    FormsModule,
    LayoutModule,
    WindowModule,
    ButtonsModule,
    BrowserAnimationsModule,
    KendoControlModule,
    NgMultiSelectDropDownModule,
    TlmUtilsRoutingModule,
    TreeViewModule,
    MappingModule,
    TranslateModule,
    ChartsModule,
    DialogsModule,
    ProgressBarModule,
    ReactiveFormsModule,
    TooltipModule
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  exports: [ClassificationComponent],
})
export class TLMUtilsModule {}
