/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using System;
using System.Collections.Generic;
using FMP.Model.LayoutDataModel;

namespace FMP.Model.UserProfileDataModel
{
    public class UserProfileRequestData
    {
        public int ProfileID { get; set; }
        public string UserID { get; set; }
        public string LastApplicationName { get; set; }
        public DateTime CreationTimestamp { get; set; }
        public DateTime LastUpdateTimestamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsActive { get; set; }
        public LayoutData LayoutData { get; set; }
    }

    public class LayoutData
    {
        public int LayoutID { get; set; }

        //public string UserID { get; set; }
        public string ApplicationName { get; set; }

        public string LayoutName { get; set; }

        public string LayoutType { get; set; }
        public List<LayoutConfig> LayoutConfigs { get; set; }
        public ActiveLayoutsData ActiveLayoutsData { get; set; }
        public FilterConfigs Filter { get; set; }
        public List<GroupConfigs> Group { get; set; }
        public List<SortConfigs> Sort { get; set; }
    }

    public class ActiveLayoutsData
    {
        public string UserID { get; set; }
        public string ApplicationName { get; set; }
    }
}