/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { NgModule } from '@angular/core';
import { ButtonsModule, ButtonGroupModule, DropDownButtonModule, SplitButtonModule } from '@progress/kendo-angular-buttons';
import {
    DatePickerModule, TimePickerModule, CalendarModule,
    DateInputModule, DateRangeModule, MultiViewCalendarModule
} from '@progress/kendo-angular-dateinputs';
import { AutoCompleteModule, ComboBoxModule, DropDownListModule, DropDownsModule } from '@progress/kendo-angular-dropdowns';
import { DialogsModule, WindowModule, } from '@progress/kendo-angular-dialog';
import { ExcelExportModule } from '@progress/kendo-angular-excel-export';
import {
    GridModule, ExcelModule, BodyModule, FilterMenuModule, FooterModule,
    GroupModule, HeaderModule, PagerModule, PDFModule, SharedModule
} from '@progress/kendo-angular-grid';
import {
    InputsModule, SwitchModule, MaskedTextBoxModule,
    SliderModule, TextBoxModule, NumericTextBoxModule
} from '@progress/kendo-angular-inputs';
import { LabelModule } from '@progress/kendo-angular-label';
import { LayoutModule, PanelBarModule, SplitterModule, TabStripModule } from '@progress/kendo-angular-layout';
import { MenusModule, ContextMenuModule } from '@progress/kendo-angular-menu';
import { NotificationModule } from '@progress/kendo-angular-notification';
import { PDFExportModule } from '@progress/kendo-angular-pdf-export';
import { PopupModule } from '@progress/kendo-angular-popup';
import { SortableModule } from '@progress/kendo-angular-sortable';
import { ChatModule } from '@progress/kendo-angular-conversational-ui';

@NgModule({
    imports: [
        //#region Buttons Module
        ButtonsModule,
        ButtonGroupModule,
        DropDownButtonModule,
        SplitButtonModule,
        //#endregion Buttons Module

        //#region Date Time Picker Module
        DatePickerModule,
        TimePickerModule,
        CalendarModule,
        DateInputModule,
        DateRangeModule,
        MultiViewCalendarModule,
        //#endregion Date Time Picker Module

        //#region Dialogs Module
        DialogsModule,
        WindowModule,
        //#endregion Dialogs Module

        //#region Drop Downs Module
        AutoCompleteModule,
        ComboBoxModule,
        DropDownListModule,
        DropDownsModule,
        //#endregion Drop Downs Module

        //#region Excel Export Module
        ExcelExportModule,
        //#endregion Excel Export Module

        //#region Grid Modules
        GridModule,
        ExcelModule,
        BodyModule,
        FilterMenuModule,
        FooterModule,
        GroupModule,
        HeaderModule,
        PagerModule,
        PDFModule,
        SharedModule,
        //#endregion Grid Modules

        //#region Input Modules
        InputsModule,
        SwitchModule,
        MaskedTextBoxModule,
        SliderModule,
        TextBoxModule,
        NumericTextBoxModule,
        //#endregion Input Modules

        //#region Label Module
        LabelModule,
        //#endregion

        //#region Layout Modules
        LayoutModule,
        PanelBarModule,
        SplitterModule,
        TabStripModule,
        //#endregion Layout Module

        //#region Menu Modules
        MenusModule,
        ContextMenuModule,
        //#endregion Menu Modules

        //#region Notification Module
        NotificationModule,
        //#endregion Notification Module

        //#region PDF Export Module
        PDFExportModule,
        //#endregion PDF Export Module

        //#region Popup Module
        PopupModule,
        //#endregion

        //#region Sortable Module
        SortableModule,
        //#endregion Sortable Module

        //#region ChatModule Module
        ChatModule,
        //#endregion ChatModule Module
    ],
    declarations: [],
    providers: [],
    exports: [
        //#region Buttons Module
        ButtonsModule,
        ButtonGroupModule,
        DropDownButtonModule,
        SplitButtonModule,
        //#endregion Buttons Module

        //#region Date Time Picker Module
        DatePickerModule,
        TimePickerModule,
        CalendarModule,
        DateInputModule,
        DateRangeModule,
        MultiViewCalendarModule,
        //#endregion Date Time Picker Module

        //#region Dialogs Module
        DialogsModule,
        WindowModule,
        //#endregion Dialogs Module

        //#region Drop Downs Module
        AutoCompleteModule,
        ComboBoxModule,
        DropDownListModule,
        DropDownsModule,
        //#endregion Drop Downs Module

        //#region Excel Export Module
        ExcelExportModule,
        //#endregion Excel Export Module

        //#region Grid Modules
        GridModule,
        ExcelModule,
        BodyModule,
        FilterMenuModule,
        FooterModule,
        GroupModule,
        HeaderModule,
        PagerModule,
        PDFModule,
        SharedModule,
        //#endregion Grid Modules

        //#region Input Modules
        InputsModule,
        SwitchModule,
        MaskedTextBoxModule,
        SliderModule,
        TextBoxModule,
        NumericTextBoxModule,
        //#endregion Input Modules

        //#region Label Module
        LabelModule,
        //#endregion

        //#region Layout Modules
        LayoutModule,
        PanelBarModule,
        SplitterModule,
        TabStripModule,
        //#endregion Layout Module

        //#region Menu Modules
        MenusModule,
        ContextMenuModule,
        //#endregion Menu Modules

        //#region Notification Module
        NotificationModule,
        //#endregion Notification Module

        //#region PDF Export Module
        PDFExportModule,
        //#endregion PDF Export Module

        //#region Popup Module
        PopupModule,
        //#endregion

        //#region Sortable Module
        SortableModule,
        //#endregion Sortable Module

        //#region ChatModule Module
        ChatModule,
        //#endregion ChatModule Module
    ]
})
export class KendoControlModule { }
