/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
export class ApplicationStateModel {
    constructor() {
        this.IsAuthenticated = false;
        this.Authorization = new ApplicationAuthorizationModel();
    }

    Title: string;
    BuildVersion: string;
    Banner: string;
    IsAuthenticated: boolean;
    Authorization: ApplicationAuthorizationModel;

    IsNavigationPanelOpen: boolean;
    Configuration: any;

    get IsLoggedIn(): boolean {
        return this.IsAuthenticated && this.Authorization && this.Authorization.IsAuthorized;
    }
}

export class ApplicationAuthorizationModel {
    constructor() {
        this.IsAuthorized = false;

        this.General = new GeneralAuthorizationModel();
        this.Dashboard = new DashboardAuthorizationModel();
        this.PlanningAndScheduling = new PnSAuthorizationModel();
        this.ActivityMonitor = new ActivityMonitorAuthorizationModel();

    }

    IsAuthorized: boolean;

    General: GeneralAuthorizationModel;
    Dashboard: DashboardAuthorizationModel;
    PlanningAndScheduling: PnSAuthorizationModel;
    ActivityMonitor: ActivityMonitorAuthorizationModel;
    WorkCenter: WorkCenterAuthorizationModel;
    Administration: AdministrationAuthorizationModel;
}

abstract class BaseAuthorizationModel {
    constructor() {
        this.HasAccess = true;
    }
    HasAccess: boolean;
}
class GeneralAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

class DashboardAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

class PnSAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

class ActivityMonitorAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

class WorkCenterAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

class AdministrationAuthorizationModel extends BaseAuthorizationModel {
    constructor() {
        super();
    }
}

