'use strict';
var __extends =
  (this && this.__extends) ||
  (function() {
    var extendStatics =
      Object.setPrototypeOf ||
      ({ __proto__: [] } instanceof Array &&
        function(d, b) {
          d.__proto__ = b;
        }) ||
      function(d, b) {
        for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
      };
    return function(d, b) {
      extendStatics(d, b);
      function __() {
        this.constructor = d;
      }
      d.prototype =
        b === null
          ? Object.create(b)
          : ((__.prototype = b.prototype), new __());
    };
  })();
Object.defineProperty(exports, '__esModule', { value: true });
/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
var ApplicationStateModel = /** @class */ (function() {
  function ApplicationStateModel() {
    this.IsAuthenticated = false;
    this.Authorization = new ApplicationAuthorizationModel();
  }
  Object.defineProperty(ApplicationStateModel.prototype, 'IsLoggedIn', {
    get: function() {
      return (
        this.IsAuthenticated &&
        this.Authorization &&
        this.Authorization.IsAuthorized
      );
    },
    enumerable: true,
    configurable: true,
  });
  return ApplicationStateModel;
})();
exports.ApplicationStateModel = ApplicationStateModel;
var ApplicationAuthorizationModel = /** @class */ (function() {
  function ApplicationAuthorizationModel() {
    this.IsAuthorized = false;
    this.General = new GeneralAuthorizationModel();
    this.Dashboard = new DashboardAuthorizationModel();
    this.PlanningAndScheduling = new PnSAuthorizationModel();
    this.ActivityMonitor = new ActivityMonitorAuthorizationModel();
  }
  return ApplicationAuthorizationModel;
})();
exports.ApplicationAuthorizationModel = ApplicationAuthorizationModel;
var BaseAuthorizationModel = /** @class */ (function() {
  function BaseAuthorizationModel() {
    this.HasAccess = true;
  }
  return BaseAuthorizationModel;
})();
var GeneralAuthorizationModel = /** @class */ (function(_super) {
  __extends(GeneralAuthorizationModel, _super);
  function GeneralAuthorizationModel() {
    return _super.call(this) || this;
  }
  return GeneralAuthorizationModel;
})(BaseAuthorizationModel);
var DashboardAuthorizationModel = /** @class */ (function(_super) {
  __extends(DashboardAuthorizationModel, _super);
  function DashboardAuthorizationModel() {
    return _super.call(this) || this;
  }
  return DashboardAuthorizationModel;
})(BaseAuthorizationModel);
var PnSAuthorizationModel = /** @class */ (function(_super) {
  __extends(PnSAuthorizationModel, _super);
  function PnSAuthorizationModel() {
    return _super.call(this) || this;
  }
  return PnSAuthorizationModel;
})(BaseAuthorizationModel);
var ActivityMonitorAuthorizationModel = /** @class */ (function(_super) {
  __extends(ActivityMonitorAuthorizationModel, _super);
  function ActivityMonitorAuthorizationModel() {
    return _super.call(this) || this;
  }
  return ActivityMonitorAuthorizationModel;
})(BaseAuthorizationModel);
var WorkCenterAuthorizationModel = /** @class */ (function(_super) {
  __extends(WorkCenterAuthorizationModel, _super);
  function WorkCenterAuthorizationModel() {
    return _super.call(this) || this;
  }
  return WorkCenterAuthorizationModel;
})(BaseAuthorizationModel);
var AdministrationAuthorizationModel = /** @class */ (function(_super) {
  __extends(AdministrationAuthorizationModel, _super);
  function AdministrationAuthorizationModel() {
    return _super.call(this) || this;
  }
  return AdministrationAuthorizationModel;
})(BaseAuthorizationModel);
//# sourceMappingURL=applicationmodels.js.map
