/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { HttpClient, HttpRequest, HttpResponse } from '@angular/common/http';

import { MateoQueue, MateoQueueStatus } from 'src/app/base/models/mateoQueue';
import * as LO from 'lodash';
import { Injectable } from '@angular/core';
import { Subject } from 'rxjs';

export class Polling {

    constructor(private http: HttpClient) {

    }

    public static unAuthorizedObservable:Subject<boolean>;
    public static mateoQueue: Map<string, MateoQueue<any>> = new Map<string, MateoQueue<any>>();

    public static addQueue<T>(queue: MateoQueue<T>): void {
        if (queue.isValid) {
            if (!this.mateoQueue.has(queue.apiurl)) {
                queue.status = MateoQueueStatus.QUEUED;
                this.mateoQueue.set(queue.apiurl, queue);
            } else {
                const existQ = this.mateoQueue.get(queue.apiurl);
                if (!existQ.HasToProcess) {
                    queue.status = MateoQueueStatus.QUEUED;
                    this.mateoQueue.set(queue.apiurl, queue);
                }
            }
        } else {
            queue.status = MateoQueueStatus.FAILED;
            alert(queue.validationMessages);
        }
    }

    public static GetQueue(apiurl: string): MateoQueue<any> {
        return this.mateoQueue.has(apiurl) ? this.mateoQueue.get(apiurl) : null;
    }

    public static RemoveQueue(apiurl: string): void {
        if (this.mateoQueue.has(apiurl)) {
            this.mateoQueue.delete(apiurl);
        }
    }

    public static AbortQueueItems(abortItems: MateoQueue<any>[]) {
        if (abortItems && abortItems.length > 0) {
            abortItems.forEach(queue => {
                this.RemoveQueue(queue.apiurl);
                queue.callbackSubject = null;
                queue.errorCallbackSubject = null;
            });
        }
    }
}
