/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */

export interface IFMPRole {
    id: number;
    name: string;
    desciption: string;
    isActive: boolean;
    mappedCMMSRoles: Array<number>;
    mappedClaims: Array<number>;
}

export class FMPRole implements IFMPRole {
    constructor(_fmpRole: IFMPRole) {
        if (_fmpRole) {
            this.id = _fmpRole.id;
            this.name = _fmpRole.name;
            this.desciption = _fmpRole.desciption;
            this.isActive = _fmpRole.isActive;
            this.mappedCMMSRoles = _fmpRole.mappedCMMSRoles;
            this.mappedClaims = _fmpRole.mappedClaims;
            this.cmmsRoleList = [];
            this.mappedClaimsList = [];
        }
    }
    id: number;
    name: string;
    desciption: string;
    isActive: boolean;
    mappedCMMSRoles: Array<number>;
    mappedClaims: Array<number>;
    cmmsRoleList: CMMSRole[];
    mappedClaimsList: Claim[];
}

export interface ICMMSRole {
    id: number;
    name: string;
    desciption: string;
    isActive: boolean;
    cmmssystem: string;
}

export class CMMSRole implements ICMMSRole {
    constructor(_cmmsRole: ICMMSRole) {
        this.id = _cmmsRole.id;
        this.name = _cmmsRole.name;
        this.desciption = _cmmsRole.desciption;
        this.isActive = _cmmsRole.isActive;
        this.cmmssystem = _cmmsRole.cmmssystem;
    }
    id: number;
    name: string;
    desciption: string;
    isActive: boolean;
    cmmssystem: string;
}


export interface IClaim {
    id: number;
    code: string;
    description: string;
    isActive: boolean;
    cmmssystem: string;
}

export class Claim implements IClaim {
    constructor(_claim: IClaim) {
        this.id = _claim.id;
        this.code = _claim.code;
        this.description = _claim.description;
        this.isActive = _claim.isActive;
        this.cmmssystem = _claim.cmmssystem;
    }
    id: number;
    code: string;
    description: string;
    isActive: boolean;
    cmmssystem: string;
}

export class RoleViewModel {
    constructor(_data: RoleDataModel) {
        this.data = _data;
    }
    public data: RoleDataModel;
}

export class RoleDataModel {
    public fmpRole: FMPRole[];
    public cmmsRole: CMMSRole[];
    public claim: Claim[];
}
