/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
export interface ISubSite {
  attribute: string;
  name: string;
  description: string;
}

export interface IBusinessView {
  businessGroup: string;
  code: string;
  definition: string;
  longName: string;
  owner: string;
  parentCode: string;
  type: string;
  reportName: string;
}

export interface IFacility {
  areaCode: string;
  facilityPhone: string;
  facilityStatus: string;
  facilityType: string;
  geoMarketCode: string;
  geoSiteId: string;
  geoSiteName: string;
  id: string;
  latitude: string;
  longitude: string;
  name: string;
  ownerShip: string;
}

export interface ISite {
  code: string;
  description: string;
  name: string;
  siteKey: string;
  siteType: string;
  facilityId: string;
  geoMarketCode: string;
  facilityName: string;
  segmentCode: string;
  facility: IFacility;
  businessView: IBusinessView;
  subSite: ISubSite[];
  createdDate: string;
  createdBy: string;
  modifiedDate: string;
  modifiedBy: string;
  activeCMMS: string;
  sourceSystemId: string;
  sourceRecordId: string;
}


export class SubSite implements ISubSite {
  constructor(_subSite: ISubSite) {
    this.attribute = _subSite.attribute;
    this.name = _subSite.name;
    this.description = _subSite.description;
  }
  attribute: string;
  name: string;
  description: string;
}

export class BusinessView implements IBusinessView {
  constructor(_businessView: IBusinessView) {
    this.businessGroup = _businessView.businessGroup;
    this.code = _businessView.code;
    this.definition = _businessView.definition;
    this.longName = _businessView.longName;
    this.owner = _businessView.owner;
    this.parentCode = _businessView.parentCode;
    this.type = _businessView.type;
    this.reportName = _businessView.reportName;
  }
  businessGroup: string;
  code: string;
  definition: string;
  longName: string;
  owner: string;
  parentCode: string;
  type: string;
  reportName: string;
}

export class Facility implements IFacility {
  constructor(_facility: IFacility) {
    this.areaCode = _facility.areaCode;
    this.facilityPhone = _facility.facilityPhone;
    this.facilityStatus = _facility.facilityStatus;
    this.facilityType = _facility.facilityType;
    this.geoMarketCode = _facility.geoMarketCode;
    this.geoSiteId = _facility.geoSiteId;
    this.geoSiteName = _facility.geoSiteName;
    this.id = _facility.id;
    this.latitude = _facility.latitude;
    this.longitude = _facility.longitude;
    this.name = _facility.name;
    this.ownerShip = _facility.ownerShip;
  }
  areaCode: string;
  facilityPhone: string;
  facilityStatus: string;
  facilityType: string;
  geoMarketCode: string;
  geoSiteId: string;
  geoSiteName: string;
  id: string;
  latitude: string;
  longitude: string;
  name: string;
  ownerShip: string;
}

export class Site implements ISite {
  constructor(_site: ISite) {
    this.code = _site.code;
    this.description = _site.description;
    this.name = _site.name;
    this.siteKey = _site.siteKey;
    this.siteType = _site.siteType;
    this.facilityId = _site.facilityId;
    this.geoMarketCode = _site.geoMarketCode;
    this.facilityName = _site.facilityName;
    this.segmentCode = _site.segmentCode;
    this.facility = _site.facility;
    this.businessView = _site.businessView;
    this.subSite = _site.subSite;
    this.createdDate = _site.createdDate;
    this.createdBy = _site.createdBy;
    this.modifiedDate = _site.modifiedDate;
    this.modifiedBy = _site.modifiedBy;
    this.activeCMMS = _site.activeCMMS;
    this.sourceSystemId = _site.sourceSystemId;
    this.sourceRecordId = _site.sourceRecordId;
  }
  code: string;
  description: string;
  name: string;
  siteKey: string;
  siteType: string;
  facilityId: string;
  geoMarketCode: string;
  facilityName: string;
  segmentCode: string;
  facility: IFacility;
  businessView: IBusinessView;
  subSite: ISubSite[];
  createdDate: string;
  createdBy: string;
  modifiedDate: string;
  modifiedBy: string;
  activeCMMS: string;
  sourceSystemId: string;
  sourceRecordId: string;
}

