/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Security.Claims;

namespace FMP.Common
{
    /// <summary>
    /// Helper Class to extract details from HttpContext.
    /// </summary>
    public static class HttpContextExtension
    {
        /// <summary>
        /// Return the first name of the User from the HttpContext(Bearer Token).
        /// </summary>
        /// <param name="httpContext">Http Context</param>
        /// <returns></returns>
        public static string GetUserFirstName(this HttpContext httpContext)
        {
            if (httpContext != null)
            {
                Claim claim = httpContext.User.FindFirst(x => x.Type == ClaimTypes.GivenName);
                return claim != null ? claim.Value : string.Empty;
            }
            return string.Empty;
        }

        /// <summary>
        /// Return the last name of the User from the HttpContext(Bearer Token).
        /// </summary>
        /// <param name="httpContext">Http Context</param>
        /// <returns></returns>
        public static string GetUserLastName(this HttpContext httpContext)
        {
            if (httpContext != null)
            {
                Claim claim = httpContext.User.FindFirst(x => x.Type == ClaimTypes.Surname);
                return claim != null ? claim.Value : string.Empty;
            }
            return string.Empty;
        }

        public static string GetUserFullName(this HttpContext httpContext)
        {
            return $"{httpContext.GetUserFirstName()} {httpContext.GetUserLastName()}";
        }

        /// <summary>
        /// Return the email of the User from the HttpContext(Bearer Token).
        /// </summary>
        /// <param name="httpContext">Http Context</param>
        /// <returns></returns>
        public static string GetUserEmail(this HttpContext httpContext)
        {
            if (httpContext != null)
            {
                Claim claim = httpContext.User.FindFirst(x => x.Type == ClaimTypes.Upn);
                return claim != null ? claim.Value : string.Empty;
            }
            return string.Empty;
        }

        /// <summary>
        /// Return the ldap of the User from the HttpContext(Bearer Token).
        /// </summary>
        /// <param name="httpContext">Http Context</param>
        /// <returns></returns>
        public static string GetUserLDAP(this HttpContext httpContext)
        {
            if (httpContext != null)
            {
                Claim claim = httpContext.User.FindFirst(x => x.Type == ClaimTypes.Upn);
                string ldap = claim?.Value.Split(new[] { '@' }).FirstOrDefault();
                return string.IsNullOrWhiteSpace(ldap) ? "unknown" : ldap.ToLowerInvariant();
            }
            return "unknown";
        }
    }
}
