/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { Component, OnInit, TemplateRef, ViewChild, OnChanges } from '@angular/core';
import { BsModalService, BsModalRef } from 'ngx-bootstrap';
import { UserProfileViewModel, UserProfile } from '../../../../base/models/userprofile';
import { UserprofileService } from '../../../../base/userprofile/userprofile.service';
import * as moment from 'moment';
import { PatchJson } from '../../../../base/models/patchjson';
@Component({
  selector: 'app-notification-popup',
  templateUrl: './notification-popup.component.html',
  styleUrls: ['./notification-popup.component.scss']
})
export class NotificationPopupComponent implements OnInit, OnChanges {

    @ViewChild('notificationPopUpTemplate', { static: false }) notificationPopUpTemplate: TemplateRef<any>;
  modalRef: BsModalRef;
  popUpHeaderTitle: string;
  hideNotificationPopUp: boolean;
  public userProfileViewModel: UserProfileViewModel;
  public lastReleaseNoteDismissid: number;
  public releaseNoteid: number;
  public popUpHtmlString: string;
  public startDate: Date;
  public outageHours: string;
  constructor(private modalService: BsModalService, private _userProfileService: UserprofileService, ) {
  }

    ngOnInit() {
   // Allan remove
   // this._userProfileService.getReleaseNote().subscribe(result => {
   //   this.releaseNoteid = result.releaseNoteid;
   //   this.lastReleaseNoteDismissid = this._userProfileService.dataModel.user.lastReleaseNoteDismiss;
   //   this.popUpHtmlString = result.releaseNotes;
   //   this.startDate = result.downTimeStart;
   //   this.outageHours = this.getHoursDifference(result.downTimeStart, result.downTimeEnd);
   //   if (this.releaseNoteid > this.lastReleaseNoteDismissid && result.isAvtive) {
   //     this.openNotificationPopUp();
  //  }
   // });
  //  this.popUpHeaderTitle = 'System Notification';
  //  this.hideNotificationPopUp = false;
  }

  ngOnChanges() {
  }
  openNotificationPopUp() {
    this.modalRef = this.modalService.show(this.notificationPopUpTemplate);
  }

  closeNotificationPopUp() {
    this.modalRef.hide();
  }

  updateNotificationPreferences(hideNotificationPopUp: boolean) {
    const userProfile: UserProfile = this._userProfileService.dataModel.user;
    if (hideNotificationPopUp) {
      const patch: PatchJson = {
        value: (userProfile.lastReleaseNoteDismiss != null ?  this.releaseNoteid : 0).toString(),
        path: '/LastReleaseNoteDismiss',
        op: 'Update'
      };
      userProfile.lastReleaseNoteDismiss = userProfile.lastReleaseNoteDismiss != null ? this.releaseNoteid : 0;

      this._userProfileService.UpdateReleaseNoteSetting(userProfile.ldapAlias, patch).subscribe(success => {
      }, err => {
        // this.WriteErrorLog('User Preference save failed.', err);
      });
    }
    this.modalRef.hide();
  }

  getHoursDifference(startDate: string, endDate: string) {
    const sDate = moment(startDate, 'YYYY-MM-DD HH:mm:ss');
    const eDate = moment(endDate, 'YYYY-MM-DD HH:mm:ss');
    const duration: string = moment.duration(eDate.diff(sDate)).asHours().toFixed(2);
    return duration;
  }
}
