/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using System.Collections.Generic;
using System.Threading.Tasks;
using FMP.Model.UserProfileDataModel;

namespace FMP.Service.UserProfile.Interface
{
    public interface IUserProfileService
    {
        Task<ColumnOptionData> GetUserProfile(string userId, string applicationName);

        Task<bool> SaveUserProfile(UserProfileRequestData userProfileRequestData);

        Task<bool> SaveLastApplicationName(string Ldap, string applicationName);

        Task<string> GetLastApplicationName(string Ldap);

        Task<bool> UpdateActiveLayout(UserActiveLayoutRequestData userActiveLayoutRequestData);

        Task<IReadOnlyList<Model.UserProfileDataModel.UserProfile>> GetUserRoleLocation(string LDAP);

        Task<bool> SaveUserRoleLocation(UserRoleLocationRequestData userRoleLocationRequestData);

        Task<bool> SaveUserRoleLocationList(List<MultipleUserRoleLocationRequestData> userRoleLocationRequestData);


        Task<bool> SaveRefreshIntervalInformation(string Ldap, string applicationName, int refreshInterval);

        Task<bool> SaveUserPreference(Model.UserProfileDataModel.UserProfile profile);

        Task<bool> UpdateDbLayoutColumnMappings(string appName, string fromColumn, string toColumn);
        Task<bool> SaveReleaseNoteSetting(UserJsonPatchReleaseNote profile);
    }
}