#region Schlumberger Private
/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>
#endregion

using System;
using System.Collections.Generic;
using System.Text;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using MongoDB.Driver;

namespace FMP.Model.CounterDataModel
{
    /// <summary>
    /// Counter class
    /// </summary>
    public class Counter
    {
        public ObjectId _id { get; set; }
        public int ID { get; set; }
        public int SiteCounter { get; set; }
        public int WorkStationCounter { get; set; }
        public int SchedulerCounter { get; set; }
        public int ClassificationCounter { get; set; }
        public int LanguageCounter { get; set; }

        public int RoleCounter { get; set; }
        public int CMMSRoleCounter { get; set; }
        public int ClaimCounter { get; set; }
        public int EquipmentRIMEIndices { get; set; }

        public int LayoutCounter { get; set; }
    }
}
