#region Schlumberger Private
/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>
#endregion

using System.Threading.Tasks;

namespace FMP.Repository.Counter.Interface
{
    /// <summary>
    /// ICounterRepository interface
    /// </summary>
    public interface ICounterRepository
    {
        Task<FMP.Model.CounterDataModel.Counter> GetCounter();
        Task<int> GetNextSiteID();
        Task<int> GetNextWorkStationID();
        Task<int> GetNextSchedulerID();
        Task<int> GetNextClassificationID();
        Task<int> GetNextLanguageID();
        Task<int> GetNextRoleID();
        Task<int> GetNextClaimID();
        Task<int> GetNextCMMSRoleID();
        Task<int> GetNextEquipmentRIMEIndicesID();
        Task<int> GetNextLayoutID();

    }
}
