/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { GridColumn } from '../app/sharedcomponents/models/sharedmodels';

// Admin screen columns class
export class AdminScreencolumns {
  public GridColumn: GridColumn[];
  AllColumns: GridColumn[] = [];
  // TODO : Redo variable names
  /* tslint:disable variable-name */
  LDAP_Alias: GridColumn;
  First_Name: GridColumn;
  Last_Name: GridColumn;
  Role_Name: GridColumn;
  WorkCenter: GridColumn;
  Country: GridColumn;
  Role_ID: GridColumn;
  JobCodeHRIS: GridColumn;
  Employee_No: GridColumn;
  Job_Title: GridColumn;
  Job_DescriptionHRIS: GridColumn;
  E_Mail: GridColumn;

  Name: GridColumn;
  Type: GridColumn;
  Description: GridColumn;
  Schedule_Hours: GridColumn;
  Assigned_Site: GridColumn;
  Attribute1: GridColumn;
  Attribute2: GridColumn;
  Attribute3: GridColumn;
  Action1: GridColumn;
  Action2: GridColumn;
  Action3: GridColumn;
  Action4: GridColumn;
  Action5: GridColumn;
  Action6: GridColumn;
  /* tslint:enable variable-name */

  constructor() {
    this.LDAP_Alias = new GridColumn('LDAP_Alias', 105);
    this.First_Name = new GridColumn('First_Name', 100);
    this.Last_Name = new GridColumn('Last_Name', 120);
    this.Job_Title = new GridColumn('Job_Title', 115);
    this.Job_DescriptionHRIS = new GridColumn('Job_DescriptionHRIS', 140);
    this.E_Mail = new GridColumn('e-mail', 155);
    this.Role_Name = new GridColumn('Role_Name', 140);
    this.JobCodeHRIS = new GridColumn('JobCodeHRIS', 110);
    this.Employee_No = new GridColumn('Employee_No', 85);
    this.WorkCenter = new GridColumn('WorkCenter', 195);
    this.Country = new GridColumn('Country', 75);
    this.Role_ID = new GridColumn('Role_ID', 65);

    this.Name = new GridColumn('Name', 105);
    this.Type = new GridColumn('Type', 85);
    this.Description = new GridColumn('Description', 140);
    this.Schedule_Hours = new GridColumn('Schedule_Hours', 120);
    this.Assigned_Site = new GridColumn('Assigned_Site', 140);
    this.Attribute1 = new GridColumn('Attribute1', 85);
    this.Attribute2 = new GridColumn('Attribute2', 85);
    this.Attribute3 = new GridColumn('Attribute3', 85);
    this.Action1 = new GridColumn('Action1', 85);
    this.Action2 = new GridColumn('Action2', 85);
    this.Action3 = new GridColumn('Action3', 85);
    this.Action4 = new GridColumn('Action4', 85);
    this.Action5 = new GridColumn('Action5', 85);
    this.Action6 = new GridColumn('Action6', 85);

    this.AllColumns.push(this.LDAP_Alias);
    this.AllColumns.push(this.First_Name);
    this.AllColumns.push(this.Last_Name);
    this.AllColumns.push(this.Role_Name);
    this.AllColumns.push(this.JobCodeHRIS);
    this.AllColumns.push(this.Employee_No);
    this.AllColumns.push(this.Job_Title);
    this.AllColumns.push(this.Job_DescriptionHRIS);
    this.AllColumns.push(this.WorkCenter);
    this.AllColumns.push(this.Country);
    this.AllColumns.push(this.Role_ID);
    this.AllColumns.push(this.E_Mail);

    this.AllColumns.push(this.Name);
    this.AllColumns.push(this.Type);
    this.AllColumns.push(this.Description);
    this.AllColumns.push(this.Schedule_Hours);
    this.AllColumns.push(this.Assigned_Site);
    this.AllColumns.push(this.Attribute1);
    this.AllColumns.push(this.Attribute2);
    this.AllColumns.push(this.Attribute3);
    this.AllColumns.push(this.Action1);
    this.AllColumns.push(this.Action2);
    this.AllColumns.push(this.Action3);
    this.AllColumns.push(this.Action4);
    this.AllColumns.push(this.Action5);
    this.AllColumns.push(this.Action6);
  }
}

export class PlanandScheduleScreencolumns {
  public GridColumn: GridColumn[];
  AllColumns: GridColumn[] = [];
  /* tslint:disable variable-name */
  Equipment_Code: GridColumn;
  Serial_Number: GridColumn;
  WO_Type_Level: GridColumn;
  Status1: GridColumn;
  Status2: GridColumn;
  Status3: GridColumn;
  Status4: GridColumn;
  Status5: GridColumn;
  Located: GridColumn;
  WO_Number: GridColumn;
  Duration: GridColumn;
  Planned_Start_Date: GridColumn;
  Planned_End_Date: GridColumn;
  WO_Assignment: GridColumn;
  Assigned_Resources: GridColumn;
  WO_Status: GridColumn;
  Association_ID: GridColumn;
  Toolset_Name: GridColumn;
  Located_Site_Name: GridColumn;
  Days_in_Located_Site: GridColumn;
  Master_Work_Order: GridColumn;
  PAU: GridColumn;
  Life: GridColumn;
  Priority: GridColumn;
  WO_Title: GridColumn;
  WO_Comments: GridColumn;
  PSD_Requested_Date: GridColumn;
  PSD_Requesting_District: GridColumn;
  WO_TMO_Status: GridColumn;
  FRNo: GridColumn;
  FR_Status: GridColumn;
  WO_TMO_EDD: GridColumn;
  Life_Details: GridColumn;
  Create_WO: GridColumn;
  Rime_Index: GridColumn;
  Equipment_Manual_Description: GridColumn;
  /* tslint:enable variable-name */
  constructor() {
    this.Equipment_Code = new GridColumn('Equipment_Code', 90);
    this.Serial_Number = new GridColumn('Serial_Number', 140);
    this.WO_Type_Level = new GridColumn('WO_Type_Level', 110);
    this.Status1 = new GridColumn('Status1', 90);
    this.Status2 = new GridColumn('Status2', 90);
    this.Status3 = new GridColumn('Status3', 90);
    this.Status4 = new GridColumn('Status4', 90);
    this.Status5 = new GridColumn('Status5', 90);
    this.Located = new GridColumn('Located', 105);
    this.WO_Number = new GridColumn('WO_Number', 80);
    this.Duration = new GridColumn('Duration', 90);
    this.WO_Assignment = new GridColumn('WO_Assignment', 90);
    this.WO_Status = new GridColumn('WO_Status', 155);
    this.Association_ID = new GridColumn('Association_ID', 110);
    this.Toolset_Name = new GridColumn('Toolset_Name', 75);
    this.Located_Site_Name = new GridColumn('Located_Site_Name', 100);
    this.Days_in_Located_Site = new GridColumn('Days_in_Located_Site', 100);
    this.Master_Work_Order = new GridColumn('Master_Work_Order', 90);
    this.Planned_Start_Date = new GridColumn('Planned_Start_Date', 260);
    this.Planned_End_Date = new GridColumn('Planned_End_Date', 260);
    this.Assigned_Resources = new GridColumn('Assigned_Resources', 185);
    this.PAU = new GridColumn('PAU', 120);
    this.Life = new GridColumn('Life', 80);
    this.Priority = new GridColumn('Priority', 85);
    this.WO_Title = new GridColumn('WO_Title', 90);
    this.WO_Comments = new GridColumn('WO_Comments', 90);
    this.PSD_Requested_Date = new GridColumn('PSD_Requested_Date', 140);
    this.PSD_Requesting_District = new GridColumn(
      'PSD_Requesting_District',
      120,
    );
    this.WO_TMO_Status = new GridColumn('WO_TMO_Status', 110);
    this.FRNo = new GridColumn('FRNo', 65);
    this.FR_Status = new GridColumn('FR_Status', 90);
    this.WO_TMO_EDD = new GridColumn('WO_TMO_EDD', 200);
    this.Life_Details = new GridColumn('Life_Details', 120);
    this.Create_WO = new GridColumn('Create_WO', 70);
    this.Rime_Index = new GridColumn('Rime_Index', 90);
    this.Equipment_Manual_Description = new GridColumn(
      'Equipment_Manual_Description',
      130,
    );
    this.AllColumns.push(this.Equipment_Code);
    this.AllColumns.push(this.Serial_Number);
    this.AllColumns.push(this.WO_Type_Level);
    this.AllColumns.push(this.Status1);
    this.AllColumns.push(this.Status2);
    this.AllColumns.push(this.Status3);
    this.AllColumns.push(this.Status4);
    this.AllColumns.push(this.Status5);
    this.AllColumns.push(this.Located);
    this.AllColumns.push(this.WO_Number);
    this.AllColumns.push(this.Duration);
    this.AllColumns.push(this.WO_Assignment);
    this.AllColumns.push(this.WO_Status);
    this.AllColumns.push(this.Association_ID);
    this.AllColumns.push(this.Toolset_Name);
    this.AllColumns.push(this.Located_Site_Name);
    this.AllColumns.push(this.Days_in_Located_Site);
    this.AllColumns.push(this.Master_Work_Order);
    this.AllColumns.push(this.PAU);
    this.AllColumns.push(this.Life);
    this.AllColumns.push(this.Planned_Start_Date);
    this.AllColumns.push(this.Planned_End_Date);
    this.AllColumns.push(this.Assigned_Resources);
    // this.AllColumns.push(this.Tech);
    // this.AllColumns.push(this.Parent_WO);
    this.AllColumns.push(this.Priority);
    this.AllColumns.push(this.WO_Comments);
    this.AllColumns.push(this.PSD_Requested_Date);
    this.AllColumns.push(this.PSD_Requesting_District);
    this.AllColumns.push(this.WO_TMO_Status);
    this.AllColumns.push(this.FRNo);
    this.AllColumns.push(this.FR_Status);
    this.AllColumns.push(this.WO_TMO_EDD);
    this.AllColumns.push(this.Life_Details);
    this.AllColumns.push(this.Create_WO);
    this.AllColumns.push(this.Rime_Index);
    this.AllColumns.push(this.Equipment_Manual_Description);
  }
}

export const FMPConstant = {
  pagingsize: [10, 20, 50, 100],
  defaultPageSize: 20,

  maxCustomLayoutNameSize: 100,
  btnCount: 5,
  userLdapKey: 'userLdap',
  activityMonitorTCOHyperLinkURL:
    'http://tlmapps.test.slb.com/TCO/index.html#/QTrac/',
  ColumnOptions: {
    maxAllowedLayouts: 20,
    maxAllowedLayoutsMessage:
      'Max No of Templates to save has been reached. Please edit/delete previous templates',
    maxAllowedPublicFavLayouts: 5,
    maxAllowedPublicFavLayoutMessage:
      'Max No of Public Favorites Templates has been reached. Please remove previous templates',
  },
  /* Resource strings (error messages, information messages) */

  /* Application Page Names */
  workCenter: 'WorkCenter',
  planandSchedule: 'PlanandSchedule',
  activityMonitor: 'ActivityMonitor',
  dashboard: 'Dashboard',
  administration: 'Administration',
  epicv3Browser: 'EpicV3Browser',
  equipmentHealth: 'EquipmentHealth',
  historianProvision: 'HistorianProvision',
  episodeBrowser: 'EpisodeBrowser',
  classificationEditor: 'ClassificationEditor',
  standardWork: 'StandardWork',
  schedulerAdmin: 'SchedulerAdmin',
  historianManagement:'HistorianManagement',
  conflictManagement:'ConflictManagement',
  addSchedulerJob: 'AddSchedulerJob',
  updateSchedulerJob: 'UpdateSchedulerJob',
  auditLog:'AuditLog',
  channelDefinition:'ChannelDefinition',
  channelDefinitionAdmin:'ChannelDefinitionAdmin',

  /* Column Option Panel Header Names */
  workCenterPanel: 'ADMIN',
  planandSchedulePanel: 'PLAN & SCHEDULE',
  activityMonitorPanel: 'ACTIVITY MONITOR',
  administrationPanel: 'Application Administration',
  tlmutilsPanel: 'TLM Utilities',

  /* Traffic Light Statuses */
  created: 'CREATED',
  shipped: 'SHIPPED',
  partiallyShipped: 'PARTIALLY SHIPPED',
  cancelled: 'CANCELLED',
  asap: 'ASAP',
  canceled: 'CANCELED',
  upcoming: 'UPCOMING',
  rejected: 'REJECTED',
  partiallRejected: 'PARTIALLY REJECTED',
  redirected: 'REDIRECTED',
  partiallyRedirected: 'PARTIALLY REDIRECTED',
  released: 'RELEASED',
  partiallyReleased: 'PARTIALLY RELEASED',
  accepted: 'ACCEPTED',
  partiallyAccepted: 'PARTIALLY ACCEPTED',
  submitted: 'SUBMITTED',
  partiallySubmitted: 'PARTIALLY SUBMITTED',
  missed: 'MISSED',

  planned: 'Planned',
  next: 'Next',
  tlm: 'Tlm',

  checkWithinHours: 24,
  numberOfDays: 30,
  staticBHPressureValue: 20000,
  staticBHTemperatureValue: 150,

  // default User
  SystemUser: 'SystemUser',
  nonRemovableColumn: 'This column cannot be removed.',
  removableColumn: 'Are you sure you want to remove this column?',
  defaultLayout: 'Default',

  // Activity Monitor
  missedCheckStatusFieldHierTCO: 'TCO_Number',

  // Fields used in Editing Dates on AM Grid
  tlmShipDate: 'TlmShipDate',
  tlmActualShipDate: 'TlmActualShipDate',
  nextShipDate: 'NextShipDate',
  // Activity Monitor

  // if we have to add any new columns in future, need to update here and also in html
  workCenterAllColumns: [
    {
      columnName: 'LDAP Alias',
      columnId: 1,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'First Name',
      columnId: 2,
      isLocked: false,
      isDefault: true,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Last Name',
      columnId: 3,
      isLocked: false,
      isDefault: true,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Role',
      columnId: 4,
      isLocked: false,
      isDefault: true,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Assigned Center',
      columnId: 5,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Country',
      columnId: 6,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Role ID',
      columnId: 7,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'JobCodeHRIS',
      columnId: 8,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Employee No',
      columnId: 9,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Job Title',
      columnId: 10,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Job DescriptionHRIS',
      columnId: 11,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'E-Mail',
      columnId: 12,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },

    {
      columnName: 'Name',
      columnId: 13,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Type',
      columnId: 14,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Description',
      columnId: 15,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Schedule-Hours',
      columnId: 16,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Assigned-Site',
      columnId: 17,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Attribute1',
      columnId: 18,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Attribute2',
      columnId: 19,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Attribute3',
      columnId: 20,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action1',
      columnId: 21,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action2',
      columnId: 22,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action3',
      columnId: 23,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action4',
      columnId: 24,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action5',
      columnId: 25,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Action6',
      columnId: 26,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
  ],
  // if we have to add any new columns in future, need to update here and also in html
  equipmentAllColumns: [
    {
      columnName: 'Equipment Code',
      columnId: 1,
      isLocked: false,
      isDefault: true,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment SN',
      columnId: 2,
      isLocked: false,
      isDefault: true,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Work Type and Level',
      columnId: 3,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment Status 1',
      columnId: 4,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment Status 2',
      columnId: 5,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment Status 3',
      columnId: 6,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment Status 4',
      columnId: 7,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Equipment Status 5',
      columnId: 8,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Located',
      columnId: 9,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Number',
      columnId: 10,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Expected Duration',
      columnId: 11,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Planned Start Date',
      columnId: 12,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Planned End Date',
      columnId: 13,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO WC Assignment',
      columnId: 14,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Employee Assigned',
      columnId: 15,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Status',
      columnId: 16,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Association ID',
      columnId: 17,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Toolset Name',
      columnId: 18,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Located Site Name',
      columnId: 19,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Days in Located Site',
      columnId: 20,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Master Work Order',
      columnId: 21,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'PAU',
      columnId: 22,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Life',
      columnId: 23,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Priority',
      columnId: 24,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Title',
      columnId: 25,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO Comments',
      columnId: 26,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'PSD Requested Date',
      columnId: 27,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'PSD Requesting District',
      columnId: 28,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO TMO Status',
      columnId: 29,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'FRNo',
      columnId: 30,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'FR Status',
      columnId: 31,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'WO TMO EDD',
      columnId: 32,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Life Details',
      columnId: 33,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
    {
      columnName: 'Create WO',
      columnId: 34,
      isLocked: false,
      isDefault: false,
      disabled: false,
      DropDownSource: new Array(),
    },
  ],

  routePages: [{ dashboard: 'dashboard' }],

  mockRoleAndSites: [
    {
      name: 'FMP Test Role 1',
      description: 'Global Administrator',
      isSelected: false,
      profile: [
        {
          profileId: '1927832',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'BRC1-TREW1',
          workLocationName: 'Oman',
          isSelected: false,
        },
        {
          profileId: '1927832',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'GBC1-TREW1',
          workLocationName: 'Oman',
          isSelected: false,
        },
        {
          profileId: '1927833',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'NOC1-TREW1',
          workLocationName: 'NOC1-TREW1',
          facility: null,
          isSelected: false,
        },
      ],
      link: null,
    },
    {
      name: 'FMP Test Role 2',
      description: 'Location Administrator',
      isSelected: false,
      profile: [
        {
          profileId: '19278653',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'IDCE-TREW1',
          workLocationName: 'Master Quasar',
          facility: null,
          isSelected: false,
        },
        {
          profileId: '19278654',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'INC1-TREW1',
          workLocationName: 'Master Quasar',
          facility: null,
          isSelected: false,
        },
        {
          profileId: '19278655',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'D&M',
          workLocation: 'MYCR-TREW1',
          workLocationName: 'MYCR-TREW1',
          facility: null,
          isSelected: false,
        },
      ],
      link: null,
    },
    {
      name: 'MAXIMO Role',
      description: 'MAXIMO Role',
      isSelected: false,
      profile: [
        {
          profileId: '19278653',
          competencyProfile: null,
          embargoLocationFlag: false,
          labourHours: '8.00',
          organization: null,
          segment: 'OST',
          workLocation: 'San Antonio',
          workLocationName: 'San Antonio',
          facility: null,
          isSelected: false,
        },
      ],
      link: null,
    },
  ],

  mvp1Sites: [
    { Site_ID: 74, workLocation: 'NGC', SiteName: 'Youngsville' },
    { Site_ID: 642, workLocation: 'NGCUSL', SiteName: 'NGCUSL' },
    { Site_ID: 837, workLocation: 'OKCTLM', SiteName: 'Oklahoma City (MB)' },
    { Site_ID: 131, workLocation: 'OKC', SiteName: 'Oklahoma City' },
    { Site_ID: 545, workLocation: 'MLD', SiteName: 'Midland' },
    { Site_ID: 128, workLocation: 'CCO', SiteName: 'Commerce City (74)' },
    { Site_ID: 599, workLocation: 'HOU', SiteName: 'Houston' },
    { Site_ID: 838, workLocation: 'CCOTLM', SiteName: 'Commerce City (CRE)' },
    { Site_ID: 844, workLocation: 'NGCTLM', SiteName: 'Youngsville (CRE)' },
    { Site_ID: 643, workLocation: 'NGCAKA', SiteName: 'NGCAKA' },
    { Site_ID: 600, workLocation: 'NEB', SiteName: 'North East Basin (91)' },
    { Site_ID: 962, workLocation: 'CCOEXTR', SiteName: 'Commerce City Rental' },

    { Site_ID: 854, workLocation: 'MEATLM', SiteName: 'MEATLM' },
    { Site_ID: 856, workLocation: 'SAUTLM', SiteName: 'SAUTLM' },
    { Site_ID: 824, workLocation: 'ADATLM', SiteName: 'ADATLM' },
    { Site_ID: 818, workLocation: 'ASATLM', SiteName: 'ASATLM' },
    { Site_ID: 899, workLocation: 'UKATLM', SiteName: 'UKATLM' },
    { Site_ID: 35, workLocation: 'MAC', SiteName: 'MAC' },
    { Site_ID: 892, workLocation: 'HTYTLM', SiteName: 'HTYTLM' },
    { Site_ID: 850, workLocation: 'MDDTLM', SiteName: 'MDDTLM' },
    { Site_ID: 852, workLocation: 'SCDTLM', SiteName: 'SCDTLM' },

    { Site_ID: 111, workLocation: 'LFFDTR', SiteName: 'NAM-NAO-LFFDTR' },
    { Site_ID: 801, workLocation: 'OKHDTR', SiteName: 'OKHDTR' },

    {
      Site_ID: 831,
      workLocation: 'TTTDTR',
      SiteName: 'NAM-NAO-TTTDTR(Trinidad)',
    },
    {
      Site_ID: 690,
      workLocation: 'AKJDTR',
      SiteName: 'NAM-NAO-AKJDTR(Alaska)',
    },
    {
      Site_ID: 832,
      workLocation: 'NFLDTR',
      SiteName: 'NAM-NAO-NFLDTR(CAN East Coast)',
    },
    { Site_ID: 17, workLocation: 'SAU', SiteName: 'MEA-KSA-SAU' },
    { Site_ID: 2016, workLocation: '2016', SiteName: 'OneSTIM' },
    { Site_ID: 201612, workLocation: '201612', SiteName: 'Midland' },
    { Site_ID: 20630, workLocation: '20630', SiteName: 'San Antonio' },
  ],

  fakeSites: [
    'INC1-TREW1',
    'IDCE-TREW1',
    'GBC1-TREW1',
    'BRC1-TREW1',
    'MYCR-TREW1',
    'NOC1-TREW1',
    'San Antonio',
    ],
    siteSegmentName: 'siteSegmentName',
    apisenum: {
        ActivityMonitor: ['EquipmentRequest'],
        PlanandSchedule: ['Workorder', 'Equipment'],
    },
};
