/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using MongoDB.Bson;
using System;
using System.Collections.Generic;
using System.Text;

namespace FMP.Model.RoleDataModel
{
    /// <summary>
    /// Claim class for the roles
    /// </summary>
    public class Claim
    {
        /// <summary>
        /// Id auto generated by Mongo DB
        /// </summary>
        public ObjectId _id { get; set; }

        /// <summary>
        /// Primary key for claim
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// Code for the claim
        /// </summary>
        public string Code { get; set; }

        /// <summary>
        /// Claim Description
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Overwrite Claim Id
        /// </summary>
        public int? OverrideClaimId { get; set; }

        /// <summary>
        /// Category of the claim (AM/PNS/ADM)
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// Is Claim Active
        /// </summary>
        public bool IsActive { get; set; }

    }
}
