/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

using FMP.Model.Common;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace FMP.Model.RoleDataModel
{
    /// <summary>
    /// Role Class for FMP Roles
    /// </summary>
    public class Role : BaseDataModel
    {
        /// <summary>
        /// Id auto generated by Mongo DB
        /// </summary>
        public ObjectId _id { get; set; }
       
        /// <summary>
        /// Primary key for Role
        /// </summary>
        public int ID { get; set; }
       
        /// <summary>
        /// Role Name
        /// </summary>
        public string Name { get; set; }
                
        /// <summary>
        /// Role Description
        /// </summary>
        public string Description { get; set; }
        
        /// <summary>
        /// Mapped CMMS roles for the FMP role
        /// </summary>
        public List<int> MappedCMMSRoles { get; set; }
        
        /// <summary>
        /// Mapped Claims for the FMP Role
        /// </summary>
        public List<int> MappedClaims { get; set; }

        /// <summary>
        /// Mapped Claims List
        /// </summary>
        [BsonIgnore]
        public List<Claim> MappedClaimsList { get; set; }
    }
}
