/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { Component, OnInit, OnDestroy } from '@angular/core';
import { AppTranslateService } from './app.translate.service';
import { UserprofileService } from 'src/app/base/userprofile/userprofile.service';
import { PollingService } from 'src/app/base/service/polling.service';
import { BaseComponent } from 'src/app/base/component/base/base.component';
import { LoggerService } from 'src/app/base/service/logger.service';
import { FMPHelper } from 'src/Constants/helpers';
import { AuthenticationHelper } from './base/helpers/AuthenticationHelper';
import {
  OidcSecurityService,
  AuthorizationState,
  AuthorizationResult,
  ConfigResult,
  OidcConfigService,
} from 'angular-auth-oidc-client';
import { Router } from '@angular/router';
import { AppService } from './app.service';
import { Subscription } from 'rxjs';
import { filter, take } from 'rxjs/operators';
import * as baseConfig from '../assets/config/base-config.json';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  providers: [AppTranslateService, UserprofileService],
})
export class AppComponent extends BaseComponent implements OnInit, OnDestroy {
  authResultSubscription: Subscription;
  isAuthSubscription: Subscription;
    unAuthorizedSubscription: Subscription;
    isAuthenticated: boolean;
    isConfigurationLoaded: boolean;
    userData: any;

  constructor(
    private pollingService: PollingService,
    loggerService: LoggerService,
      private oidcSecurityService: OidcSecurityService,
      private oidcConfigService: OidcConfigService,
    private router: Router,
    private appService: AppService,
  ) {
    super('AppComponent', loggerService);

      //if (this.oidcSecurityService.moduleSetup) {
          //debugger;
         // this.doCallbackLogicIfRequired();
          //this.postOIDCModuleSetup();
          
      //} else {
          //debugger;
         // this.oidcSecurityService.onModuleSetup.subscribe(() => {
          //    this.doCallbackLogicIfRequired();
          //});
      //}
      this.oidcSecurityService
          .getIsModuleSetup()
          .pipe(
              filter((isModuleSetup: boolean) => isModuleSetup),
              take(1),
          )
          .subscribe((isModuleSetup: boolean) => {
              this.postOIDCModuleSetup();
          });
    this.unAuthorizedSubscription = this.appService.unAuthorizedObservable.subscribe(
      () => {
        this.router.navigate([FMPHelper.Routes.UnAuthorized.path]);
      },
      () => {
        this.router.navigate([FMPHelper.Routes.FMPError.path]);
      },
    );

    this.authResultSubscription = this.oidcSecurityService.onAuthorizationResult.subscribe(
      (authorizationResult: AuthorizationResult) => {
        this.processCompletedAuthorizationResult(
          authorizationResult.authorizationState,
        );
      },
    );

    this.pollingService.StartMateoQueueMonitor();
    }
    private doCallbackLogicIfRequired() {
        // Will do a callback, if the url has a code and state parameter.
        this.oidcSecurityService.authorizedCallbackWithCode(window.location.toString());
    }

  ngOnInit() {
      this.ApplicationState.Configuration = baseConfig.default;
      this.doInit();

    }
    doInit() {
        this.oidcConfigService.onConfigurationLoaded.subscribe((value: ConfigResult) => {
            this.isConfigurationLoaded = true;
        });

        this.oidcSecurityService.getIsAuthorized().subscribe(auth => {
            this.isAuthenticated = auth;
        });

        this.oidcSecurityService.getUserData().subscribe(userData => {
            this.userData = userData;
        });
    }

  private postOIDCModuleSetup() {
    let responseHash: string = AuthenticationHelper.GetTokenHash();
    if (FMPHelper.StringIsNullOrWhiteSpace(responseHash)) {
        responseHash = FMPHelper.ReadFromLocalStorage('FMP_AUTH_RESPONSE');
    }
      
      if (!FMPHelper.StringIsNullOrWhiteSpace(responseHash)) {
      FMPHelper.WriteToLocalStorage('FMP_AUTH_RESPONSE', responseHash);
      this.oidcSecurityService.authorizedImplicitFlowCallback();
    } else {
      this.isAuthSubscription = this.oidcSecurityService
        .getIsAuthorized()
        .subscribe((authenticated: boolean) => {
          this.appService.ApplicationState.IsAuthenticated = authenticated;
          if (authenticated) {
            this.processAuthenticationSuccess();
          } else {
            this.processAuthenticationFailure();
          }
        });
    }
  }

  private processCompletedAuthorizationResult(
    authorizationResult: AuthorizationState,
  ) {
    if (authorizationResult === AuthorizationState.authorized) {
      this.processAuthenticationSuccess();
    } else {
      this.processAuthenticationFailure();
    }
  }

  private processAuthenticationSuccess() {
    if (!this.appService.ApplicationState.IsAuthenticated) {
      this.appService.ApplicationState.IsAuthenticated = true;
      this.router.navigate([FMPHelper.Routes.Home.path]);
    }
  }

  private processAuthenticationFailure() {
    this.appService.ApplicationState.IsAuthenticated = false;
    this.appService.ApplicationState.Authorization.IsAuthorized = false;
    this.router.navigate([FMPHelper.Routes.AutoLogin.path]);
  }

  ngOnDestroy() {
    this.UnsubscribeObervable(this.authResultSubscription);
    this.UnsubscribeObervable(this.isAuthSubscription);
    this.UnsubscribeObervable(this.unAuthorizedSubscription);
  }
}
