/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  NO_ERRORS_SCHEMA,
} from '@angular/core';
import {
  UserprofileServiceMock,
  LoggerServiceMock,
} from 'src/mocks/commonServicesMock.spec';
import { UserprofileService } from './base/userprofile/userprofile.service';
import { HttpClientModule } from '@angular/common/http';
import { LoggerService } from './base/service/logger.service';
import { AuthModule, OidcSecurityService } from 'angular-auth-oidc-client';
import { RouterTestingModule } from '@angular/router/testing';

// *********************************************************************
@Component({
  selector: 'app-left-navigation',
  template: '',
})
// tslint:disable-next-line:max-classes-per-file
export class LeftNavigationMockComponent {}

// *********************************************************************
@Component({
  selector: 'app-loader',
  template: '',
})
// tslint:disable-next-line:max-classes-per-file
export class LoaderMockComponent {}
// *********************************************************************
@Component({
  selector: 'app-config',
  template: '',
})
// tslint:disable-next-line:max-classes-per-file
export class ConfigMockComponent {}
// *********************************************************************
@Component({
  selector: 'app-messages',
  template: '',
})
// tslint:disable-next-line:max-classes-per-file
export class MessagesMockComponent {}

xdescribe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      schemas: [CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA],
      imports: [HttpClientModule, RouterTestingModule, AuthModule.forRoot()],
      declarations: [
        AppComponent,
        LeftNavigationMockComponent,
        LoaderMockComponent,
        MessagesMockComponent,
        ConfigMockComponent,
      ],
      providers: [
        { provide: UserprofileService, useClass: UserprofileServiceMock },
        { provide: LoggerService, useClass: LoggerServiceMock },
        OidcSecurityService,
      ],
    }).compileComponents();
  }));

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));

  it(`should have as title 'app'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).not.toBeNull();
  }));

  it('should render title in a h1 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const compiled = fixture.debugElement.nativeElement;
    // expect(compiled.querySelector('h1').textContent).toContain('Welcome to app!');
  }));
});
