#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591
using FMPUserProfile = FMP.Model.UserProfileDataModel.UserProfile;

#pragma warning disable 1591

namespace FMP.Service.UserProfile
{
    public class UserProfileFilter: EntityFilterBase<FMPUserProfile>
    {
        public static UserProfileFilter By(string userId)
        {
            var obj = new UserProfileFilter();

            var filter1 = obj.FilterBuilder.Where(
                f => f.UserID == userId
            );

            obj.Filters.Add(filter1);

            return obj;
        }

        public UserProfileFilter AndByActive(bool active)
        {
            var filter1 = FilterBuilder.Where(
                f => f.IsActive == active
            );

            Filters.Add(filter1);
            
            return this;
        }

        public UserProfileFilter AndByRole(string role)
        {
            var filter1 = FilterBuilder.Where(
                f => f.RoleName == role
            );

            Filters.Add(filter1);

            return this;
        }
    }
 }