/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import {
  Component,
  OnInit,
  TemplateRef,
  ViewEncapsulation,
  OnDestroy,
} from '@angular/core';
import { BsModalRef, BsModalService } from 'ngx-bootstrap';
import { LoggerService } from 'src/app/base/service/logger.service';
import { BaseComponent } from 'src/app/base/component/base/base.component';
import { TranslateService } from '@ngx-translate/core';
import { Router, ActivatedRoute } from '@angular/router';
import { ContextHelpService } from './contexthelp.service';
import {
  ContextHelpDataModel,
  ContextHelpDetails,
  ElementPosition,
  ContextHelpConfiguration,
  ContextHelpDirection,
} from '../models/context-help';
import { FMPHelper } from 'src/Constants/helpers';
import { Subscription } from 'rxjs';
import { ContextHelpConfigurationList } from './context-help-configuration';

@Component({
  selector: 'app-fmp-contexthelp',
  templateUrl: './contexthelp.component.html',
  styleUrls: ['./contexthelp.component.scss'],
  encapsulation: ViewEncapsulation.None,
})
export class ContexthelpComponent extends BaseComponent
  implements OnInit, OnDestroy {
  modalRef: BsModalRef;
  config = {
    backdrop: true,
    ignoreBackdropClick: true,
    class: 'contextHelpPopUP',
    keyboard: false,
  };

  contextData: ContextHelpDataModel;
  selectedContext: ContextHelpDetails;
  contextSelectionSubscription: Subscription;

  private defaultContextConfig: ContextHelpConfiguration;

  ngOnInit() {
    this.defaultContextConfig = ContextHelpConfigurationList.find(config =>
      FMPHelper.StringEqual(config.contextKey, 'context-help-default'),
    );
    this.contextSelectionSubscription = this._contextService.contextSelectionObservable.subscribe(
      context => {
        this.selectContextDetails(context);
      },
    );
  }

  ngOnDestroy() {
    this.UnsubscribeObervable(this.contextSelectionSubscription);
  }

  constructor(
    private _modalService: BsModalService,
    _loggerService: LoggerService,
    private translate: TranslateService,
    public route: ActivatedRoute,
    private _contextService: ContextHelpService,
  ) {
    super('ContexthelpComponent', _loggerService);
    this.contextData = this._contextService.dataModel;
  }

  openContextHelpPopUP(ContextHelpTemplate: TemplateRef<any>) {
    this.contextData.contextList = [];
    const contextTargets = document.querySelectorAll('[contexthelp]');
    if (contextTargets && contextTargets.length > 0) {
      Array.from(contextTargets).forEach((target, index) => {
        this.contextData.contextList.push(
          this.calculateTragetContextDetails(target, index),
        );
      });
      this.selectContextDetails(this.contextData.contextList[0]);
    }
    // this.WriteDebugLog('ContexthelpComponent => openContextHelpPopUP');
    if (!this.modalRef) {
      this.modalRef = this._modalService.show(ContextHelpTemplate, this.config);
      // document.querySelector('.modal').style['position'] = 'initial';
      // document.querySelector('.modal').style['margin-top'] = '20%';
    }
  }

  private calculateTragetContextDetails(
    target: any,
    index: number,
  ): ContextHelpDetails {
    const context: ContextHelpDetails = new ContextHelpDetails();
    context.index = index + 1;
    context.target = target;
    context.targetPosition = this.calculateTargetPosition(target);

    const contextConfig = ContextHelpConfigurationList.find(config =>
      FMPHelper.StringEqual(
        config.contextKey,
        target.getAttribute('contexthelp'),
      ),
    );
    context.config = contextConfig ? contextConfig : this.defaultContextConfig;
    context.tagPosition = this.calculateTagPosition(context);
    return context;
  }

  private calculateTargetPosition(target): ElementPosition {
    const position: ElementPosition = new ElementPosition();
    position.targetRectPosition = target.getBoundingClientRect();
    position.top = position.targetRectPosition.top;
    position.left = position.targetRectPosition.left;
    return position;
  }

  private calculateTagPosition(context: ContextHelpDetails): ElementPosition {
    const position: ElementPosition = new ElementPosition();
    const tagDimension = 30;
    const accentOffset = 4;
    switch (context.config.direction) {
      case ContextHelpDirection.Top:
        position.top =
          context.targetPosition.top - tagDimension * 1.5 - accentOffset;
        position.left =
          context.targetPosition.left +
          context.targetPosition.targetRectPosition.width / 2 -
          tagDimension / 2;
        break;
      case ContextHelpDirection.Bottom:
        position.top =
          context.targetPosition.top +
          context.targetPosition.targetRectPosition.height +
          accentOffset;
        position.left =
          context.targetPosition.left +
          context.targetPosition.targetRectPosition.width / 2 -
          tagDimension / 2;
        break;
      case ContextHelpDirection.Left:
        position.top =
          context.targetPosition.top +
          context.targetPosition.targetRectPosition.height / 2 -
          tagDimension / 2;
        position.left =
          context.targetPosition.left - tagDimension - accentOffset;
        break;
      default:
        position.top =
          context.targetPosition.top +
          context.targetPosition.targetRectPosition.height / 2 -
          tagDimension;
        position.left =
          context.targetPosition.left +
          context.targetPosition.targetRectPosition.width +
          accentOffset;
        break;
    }
    position.top = Math.round(position.top);
    position.left = Math.round(position.left);
    return position;
  }

  onCloseContextHelpModal() {
    this.contextData.contextList.forEach(ctxt => {
      ctxt.target.classList.remove('context-target-border');
    });
    this.contextData.contextList = [];
    this.modalRef.hide();
    this.modalRef = undefined;
  }

  onNextClick(index: number): void {
    const contextDetail = this.contextData.contextList.find(
      ctxt => ctxt.index === index + 1,
    );
    this.selectContextDetails(contextDetail);
  }

  onPreviousClick(index: number): void {
    const contextDetail = this.contextData.contextList.find(
      ctxt => ctxt.index === index - 1,
    );
    this.selectContextDetails(contextDetail);
  }

  selectContextDetails(context: ContextHelpDetails): void {
    if (context) {
      this.selectedContext = context;
      this.contextData.contextList.forEach(ctxt => {
        ctxt.isSelected = false;
        ctxt.target.classList.remove('context-target-border');
      });
      context.isSelected = true;
      context.target.classList.add('context-target-border');
    }
  }
}
