/* Schlumberger Private
Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
authored and generated code (including the selection and arrangement of
the source code base regardless of the authorship of individual files),
but not including any copyright interest(s) owned by a third party
related to source code or object code authored or generated by
non-Schlumberger personnel.

This source code includes Schlumberger confidential and/or proprietary
information and may include Schlumberger trade secrets. Any use,
disclosure and/or reproduction is prohibited unless authorized in
writing. */
import { Pipe, PipeTransform } from '@angular/core';
import { FMPHelper } from 'src/Constants/helpers';
import * as momenttimezone from 'moment-timezone';
import * as moment from 'moment';

@Pipe({
  name: 'timeZoneConversion'
})
export class TimeZoneConversionPipe implements PipeTransform {
  public mapper = new Map([
    ['IST', 'Asia/Calcutta'],
    ['PDT', 'Asia/Dubai'],
    ['CDT', 'America/Chicago'],
    ['EDT', 'America/New_York'],
    ['UTC', 'Africa/Abidjan']
  ]);
  transform(
    value: Date
  ): Date {
    if (value !== undefined) {
      const fromTZ = this.mapper.get('UTC');
      const fromDate = moment.utc(value).format(); // convert into UTC date format. once UTC date get it from MATEO will remove this line
      const toTZ = momenttimezone.tz.guess();
      // We are converting time zone from one to another
      const test = FMPHelper.ConvertTimeZone(fromDate, fromTZ, toTZ);
      return test;
    }
  }
}

