#region Header

// Schlumberger Private
// Copyright 2018 Schlumberger.  All rights reserved in Schlumberger
// authored and generated code (including the selection and arrangement of
// the source code base regardless of the authorship of individual files),
// but not including any copyright interest(s) owned by a third party
// related to source code or object code authored or generated by
// non-Schlumberger personnel.
// This source code includes Schlumberger confidential and/or proprietary
// information and may include Schlumberger trade secrets. Any use,
// disclosure and/or reproduction is prohibited unless authorized in
// writing.

#endregion

using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FMP.Service.Integration.Test
{
    /// <summary>
    ///     TestCategory attribute; used to specify the category of a unit test.
    /// </summary>
    [AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true)]
    public sealed class IntegrationTestCategoryAttribute : TestCategoryBaseAttribute
    {
        /// <summary>
        ///     Initializes a new instance of the
        ///     <see cref="T:Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute" /> class and applies the category
        ///     to the test.
        /// </summary>
        public IntegrationTestCategoryAttribute()
        {
            TestCategories = new List<string>(1)
            {
                "Integration"
            };
        }

        /// <summary>
        ///     Gets the test categories that has been applied to the test.
        /// </summary>
        public override IList<string> TestCategories { get; }
    }
}