#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591
using FluentAssertions;
using FMP.Model;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace FMP.Service.Integration.Test
{
    [TestClass]
    [IntegrationTestCategory]
    public class MongoDbCollectionTests : QueryHandlersTestBase
    {
        [TestInitialize]
        public void TestInitialize()
        {
            Init();
        }

        [TestMethod]
        public void Ctor_TestClass_Instantiated()
        {
            var testColl = new MongoDbCollection<TestClass>(MongoDbClient);

            testColl.GetCollectionName().Should().Be(nameof(TestClass));
        }

        [TestMethod]
        public void Ctor_TestClassCustomName_Instantiated()
        {
            var testColl = new MongoDbCollection<TestClass2>(MongoDbClient);

            testColl.GetCollectionName().Should().Be("CustomName");
        }

        private class TestClass
        {
            public string Name { get; set; }
        }

        [CollectionName("CustomName")]
        private class TestClass2
        {
            public string Name { get; set; }
        }
    }
}