/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>
using System;
using Microsoft.AspNetCore.Http;
using FMP.Common;

namespace FMP.API.Security
{
    public class IdentityService : IIdentityService
    {
        private IHttpContextAccessor _context;

        /// <summary>
        /// Creates an instance of <see cref="IdentityService"/>.
        /// </summary>
        /// <param name="context"></param>
        public IdentityService(IHttpContextAccessor context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
        }

        /// <inheritdoc />
        public string GetUserLdapLogin()
        {
            return _context.HttpContext.GetUserLDAP();
        }
    }
}
