#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591

using MongoDB.Bson;
using FMPLayout = FMP.Model.LayoutDataModel.Layout;


namespace FMP.Service.Layout
{
    public class LayoutFilter : EntityFilterBase<FMPLayout>
    {
        public static LayoutFilter By(string userId)
        {
            var obj = new LayoutFilter();

            var filter1 = obj.FilterBuilder.Where(
                f => f.UserID == userId
            );

            obj.Filters.Add(filter1);

            return obj;
        }

        public static LayoutFilter ById(ObjectId id)
        {
            var obj = new LayoutFilter();

            var filter1 = obj.FilterBuilder.Where(
                f => f._id == id
            );

            obj.Filters.Add(filter1);

            return obj;
        }

        public static LayoutFilter ByLayoutId(int id)
        {
            var obj = new LayoutFilter();

            var filter1 = obj.FilterBuilder.Where(
                f => f.LayoutID == id
            );

            obj.Filters.Add(filter1);

            return obj;
        }

        public LayoutFilter AndByAppName(string appName)
        {
            var filter1 = FilterBuilder.Where(
                f => f.ApplicationName == appName
            );

            Filters.Add(filter1);

            return this;
        }

        public LayoutFilter AndByLayoutName(string layoutName)
        {
            var filter1 = FilterBuilder.Where(
                f => f.LayoutName == layoutName
            );

            Filters.Add(filter1);

            return this;
        }

        public LayoutFilter AndByUserId(string userId)
        {
            var filter1 = FilterBuilder.Where(
                f => f.UserID == userId
            );

            Filters.Add(filter1);

            return this;
        }
    }
}