#region Header

/// <summary>
/// Schlumberger Private
/// Copyright 2018 Schlumberger.All rights reserved in Schlumberger
/// authored and generated code(including the selection and arrangement of
/// the source code base regardless of the authorship of individual files),
/// but not including any copyright interest(s) owned by a third party
/// related to source code or object code authored or generated by
/// non-Schlumberger personnel.
/// This source code includes Schlumberger confidential and/or proprietary
/// information and may include Schlumberger trade secrets.Any use,
/// disclosure and/or reproduction is prohibited unless authorized in
/// writing.
/// </summary>

#endregion

#pragma warning disable 1591

using FMP.Model.UserProfileDataModel;
using MongoDB.Driver;
using FMPLayout = FMP.Model.LayoutDataModel.Layout;


namespace FMP.Service.Layout
{
    public class UpdateLayoutCommand : UpdateBase<FMPLayout>
    {
        private UpdateLayoutCommand()
        {
        }

        public static UpdateLayoutCommand WithFilter(IQuery<FMPLayout> filter)
        {
            var obj = new UpdateLayoutCommand();
            obj.FilterInt = filter;
            return obj;
        }

        public UpdateLayoutCommand SetFrom(LayoutData layoutData)
        {
            var underStatement = UpdateBuilder
                .Set(s => s.LayoutConfigs, layoutData.LayoutConfigs)
                .Set(s => s.Sort, layoutData.Sort)
                .Set(s => s.Group, layoutData.Group)
                .Set(s => s.Filter, layoutData.Filter);

            Updates.Add(underStatement);

            return this;
        }
    }
}